server:
  port: ${SERVER_PORT:8090}
  shutdown: graceful

spring:

  application:
    name: ${SPRING_APPLICATION_NAME:auth-service}

  lifecycle:
    timeout-per-shutdown-phase: 30s

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/auth_db}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root123}


  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

    show-sql: true



eureka:

  instance:
    prefer-ip-address: true

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}



jwt:

  secret: ${JWT_SECRET}

  expiration: ${JWT_EXPIRATION:3600000}



management:

  endpoints:

    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:*}


  endpoint:

    health:
      show-details: always


  tracing:

    sampling:
      probability: ${MANAGEMENT_TRACING_SAMPLING_PROBABILITY:1.0}


    zipkin:

      tracing:

        endpoint: ${MANAGEMENT_ZIPKIN_TRACING_ENDPOINT:http://localhost:9411/api/v2/spans}



logging:

  level:

    org.springframework.security: TRACE