server:
  port: ${SERVER_PORT}
  shutdown: graceful

spring:
  application:
    name: ${SPRING_APPLICATION_NAME}

  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 100

  lifecycle:
    timeout-per-shutdown-phase: 30s

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      validation-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    show-sql: false
    open-in-view: false

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      enable-auto-commit: false

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: com.ecommerce.common.events
        spring.json.use.type.headers: true

    listener:
      ack-mode: record


eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5

    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}


management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE}

  endpoint:
    health:
      show-details: never

  prometheus:
    enabled: true

  metrics:
    tags:
      application: ${spring.application.name}

  tracing:
    sampling:
      probability: ${MANAGEMENT_TRACING_SAMPLING_PROBABILITY}

  zipkin:
    tracing:
      endpoint: ${MANAGEMENT_ZIPKIN_TRACING_ENDPOINT}


logging:
  pattern:
    level: "%5p [${spring.application.name:},trace=%X{traceId:-},span=%X{spanId:-}]"


security:
  gateway:
    enabled: true

pagination:
  default-page-size: 20
  max-page-size: 100

service:
  security:
    internal-token: ${INTERNAL_SERVICE_TOKEN}
