server:
  port: 8087

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/products/**
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/orders/**

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: localhost
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/


management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

    prometheus:
      enabled: true

  metrics:
    tags:
      application: ${spring.application.name}

  tracing:
    sampling:
      probability: 1.0

    zipkin:
      tracing:
        endpoint: http://zipkin:9411/api/v2/spans

logging:
  pattern:
    level: "%5p [${spring.application.name:},trace=%X{traceId:-},span=%X{spanId:-}]"


jwt:
  secret: MySuperSecretKeyForJwtAuthentication12345678901234567890
  expiration: 3600000