apiVersion: v1
kind: Secret

metadata:
  name: gateway-secret
  namespace: {{ .Values.namespace }}

type: Opaque

stringData:

  JWT_SECRET: MySuperSecretKeyForJwtAuthentication12345678901234567890

  JWT_EXPIRATION: "86400000"