apiVersion: v1
kind: Secret

metadata:
  name: auth-service-secret
  namespace: {{ .Values.namespace }}

type: Opaque

stringData:
  JWT_SECRET: {{ .Values.jwt.secret | quote }}

  JWT_EXPIRATION: {{ .Values.jwt.expiration | quote }}

  SPRING_DATASOURCE_USERNAME: auth_user

  SPRING_DATASOURCE_PASSWORD: auth123