apiVersion: v1
kind: Secret

metadata:
  name: auth-service-secret
  namespace: {{ .Values.namespace }}

type: Opaque

stringData:

  JWT_SECRET: MySuperSecretKeyForJwtAuthentication12345678901234567890

  JWT_EXPIRATION: "86400000"

  SPRING_DATASOURCE_USERNAME: auth_user

  SPRING_DATASOURCE_PASSWORD: auth123