apiVersion: v1
kind: Secret

metadata:
  name: cart-service-secret
  namespace: {{ .Values.namespace }}

type: Opaque

stringData:

  SPRING_DATASOURCE_USERNAME: cart_user

  SPRING_DATASOURCE_PASSWORD: cart123