apiVersion: apps/v1
kind: Deployment

metadata:

  name: eureka-server

  namespace: {{ .Values.namespace }}

spec:

  replicas: {{ .Values.eureka.replicas }}

  selector:

    matchLabels:

      app: eureka-server

  template:

    metadata:

      labels:

        app: eureka-server

    spec:

      serviceAccountName: eureka-server

      containers:

        - name: eureka-server

          image: "{{ .Values.eureka.image.repository }}:{{ .Values.eureka.image.tag }}"

          imagePullPolicy: Never

          lifecycle:
            preStop:
              exec:
                command:
                  - sh
                  - -c
                  - sleep 15

          ports:

            - containerPort: 8761

          resources:

            requests:

              cpu: "250m"

              memory: "512Mi"

            limits:

              cpu: "500m"

              memory: "1Gi"

          envFrom:

            - configMapRef:

                name: eureka-config