apiVersion: v1
kind: ConfigMap

metadata:
  name: inventory-service-config
  namespace: {{ .Values.namespace }}

data:

  SERVER_PORT: "8083"

  SPRING_APPLICATION_NAME: inventory-service

  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/inventory_db

  SPRING_JPA_HIBERNATE_DDL_AUTO: update

  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/

  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,prometheus,circuitbreakers,circuitbreakerevents,metrics"

  MANAGEMENT_TRACING_SAMPLING_PROBABILITY: "1.0"

  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans

  SECURITY_CORS_ALLOWED_ORIGINS: {{ .Values.cors.allowedOrigin | quote }}