apiVersion: v1
kind: Secret

metadata:
  name: inventory-service-secret
  namespace: {{ .Values.namespace }}

type: Opaque

stringData:

  SPRING_DATASOURCE_USERNAME: inventory_user

  SPRING_DATASOURCE_PASSWORD: inventory123