apiVersion: v1
kind: Secret

metadata:
  name: notification-service-secret
  namespace: {{ .Values.namespace }}

type: Opaque

stringData:

  SPRING_DATASOURCE_USERNAME: notification_user

  SPRING_DATASOURCE_PASSWORD: notification123

  INTERNAL_SERVICE_TOKEN: "G7vK2mQ9xR4pL8zN6cT1wY5hF3sD0aB8eU2iO9kP6j"
