apiVersion: v1
kind: Secret

metadata:
  name: order-service-secret
  namespace: {{ .Values.namespace }}

type: Opaque

stringData:

  SPRING_DATASOURCE_USERNAME: order_user

  SPRING_DATASOURCE_PASSWORD: order123