apiVersion: apps/v1
kind: Deployment

metadata:
  name: product-service
  namespace: {{ .Values.namespace }}

spec:
  replicas: {{ .Values.product.replicas }}

  revisionHistoryLimit: 10

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: product-service

  template:
    metadata:
      labels:
        app: product-service

    spec:

      terminationGracePeriodSeconds: 40

      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001

      affinity:

        podAntiAffinity:

          preferredDuringSchedulingIgnoredDuringExecution:

            - weight: 100

              podAffinityTerm:

                topologyKey: kubernetes.io/hostname

                labelSelector:

                  matchExpressions:

                    - key: app

                      operator: In

                      values:

                        - product-service

      serviceAccountName: product-service

      containers:
        - name: product-service

          image: "{{ .Values.product.image.repository }}:{{ .Values.product.image.tag }}"

          imagePullPolicy: {{ .Values.product.image.pullPolicy }}

          lifecycle:
            preStop:
              exec:
                command:
                  - sh
                  - -c
                  - sleep 15

          ports:
            - containerPort: 8089

          envFrom:
            - configMapRef:
                name: product-service-config

            - secretRef:
                name: product-service-secret

          resources:
            requests:
              cpu: {{ .Values.product.resources.requests.cpu | quote }}
              memory: {{ .Values.product.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.product.resources.limits.cpu | quote }}
              memory: {{ .Values.product.resources.limits.memory | quote }}

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8089
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8089
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3

          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8089
            failureThreshold: 30
            periodSeconds: 10