apiVersion: policy/v1
kind: PodDisruptionBudget

metadata:
  name: reviews-service-pdb
  namespace: {{ .Values.namespace }}

spec:

  minAvailable: 1

  selector:
    matchLabels:
      app: reviews-service