apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: search-service-pdb
  namespace: {{ .Values.namespace }}

spec:
  minAvailable: 1

  selector:
    matchLabels:
      app: search-service