apiVersion: v1
kind: Secret

metadata:
  name: auth-service-secret
  namespace: ecommerce

type: Opaque

stringData:
  JWT_SECRET: {{ .Values.jwt.secret | quote }}

  JWT_EXPIRATION: {{ .Values.jwt.expiration | quote }}