apiVersion: v1
kind: Secret

metadata:
  name: auth-service-secret
  namespace: ecommerce

type: Opaque

stringData:

  JWT_SECRET: MySuperSecretKeyForJwtAuthentication12345678901234567890

  JWT_EXPIRATION: "86400000"