server:
  port: 8089

spring:
  application:
    name: product-service

  datasource:
    url: jdbc:mysql://mysql:3306/product_db
    username: root
    password: root123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/


management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

    prometheus:
      enabled: true

  metrics:
    tags:
      application: ${spring.application.name}

  tracing:
    sampling:
      probability: 1.0

    zipkin:
      tracing:
        endpoint: http://zipkin:9411/api/v2/spans

logging:
  pattern:
    level: "%5p [${spring.application.name:},trace=%X{traceId:-},span=%X{spanId:-}]"